### ISSUE TITLE
Another way to find mainboard serial...

### ISSUE THREAD

**Issue by mattncsu** [drbytes/RobomowRemoteControl#2]
If you want to get your mainboard serial without having to put in your pw on an unsecured site, you can also load the https://myrobomow.robomow.com/ page with browser debugging on (F12 in Firefox).  After logging in, look at the json response to https://myrobomow.robomow.com/api/customer/products:
![screenshot](https://user-images.githubusercontent.com/24309552/60735594-15812380-9f22-11e9-9b31-db41bbbc341d.png)
I've been thinking about embedding an ESP32 (a wifi/BLE enabled microcontroller) in the robomow to enable robot control when outside of BLE range) This will give me a good starting point if I ever get around to it.

**Comment by arjanmels** [comment]
@mattncsu Nice thanks. Please note that I am already busy with implementing for ESP32 (using TTGO T-beam board, which includes GPS and Lorawan). I will publish code to github as soon as at least the basics are functional. (Hopefully in the course of this week.)

**Comment by mattncsu** [comment]
That's great! I started with a gps tracker program (https://github.com/mattncsu/ESP32_GPS_Tracker_GSM)and was planning to implement further control over the winter. Hadn't decided whether to use the BT on the ESP32 or tap the serial line directly.

**Comment by arjanmels** [comment]
I am using the BT. Pro is less connections needed, con is it blocks the app

**Comment by mattncsu** [comment]
I recall seeing an option for service mode or something like to that effect that would allow the robot to pair with any or maybe multiple devices. Might be an option

**Comment by drbytes** [comment]
Great find, I'll update the README.

**Comment by arjanmels** [comment]
@drbytes and @mattncsu Unfortunate;y, I did not yet manage to create a version that is ready to put on github. I will not be able to work on it the next couple of weeks due to holidays.

I do have the communication with the mower working and have started to decipher the protocol (using the original apk's).

**Comment by drbytes** [comment]
What are you deciphering?

**Comment by mattncsu** [comment]
Have either of you guys been able to get the bluetooth toolkit working so that (presumably) you could talk to the RM using a PC without having to physically plug in?

**Comment by drbytes** [comment]
I haven't tried tbh.
I would also need a dongle with BLE capabilities.. I have a Surface GO, I see it should be possible. Will try this weekend

**Comment by arjanmels** [comment]
@drbytes Reading of status and status messages and enabling/disabling of schedule (actually my main purpose, so i can suspend operation in wet conditions )

@mattncu which toolkit?

**Comment by drbytes** [comment]
They have a toolkit, a click once .net app. Dont have the url handy on my phone but I've used it to connect with the mower using a serial connection

**Comment by drbytes** [comment]
Closing this, it's referenced in the readme

**Comment by JohnnyPicnic** [comment]
For those with a cubcadet the url is https://cubcadet.robomow.com
